# Generated by Django 5.1.5 on 2025-01-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
