# Generated by Django 5.1.5 on 2025-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_customuser_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='frontend',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='objective',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tools',
            field=models.TextField(max_length=200),
        ),
    ]
