# Generated by Django 5.1.5 on 2025-01-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_customuser_education_alter_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tools',
        ),
        migrations.CreateModel(
            name='FormMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('objective', models.TextField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, max_length=200, null=True)),
                ('tools', models.TextField(blank=True, max_length=200, null=True)),
                ('projects', models.TextField(blank=True, max_length=500, null=True)),
                ('education', models.TextField(blank=True, max_length=500, null=True)),
                ('customuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
