# Generated by Django 5.1.5 on 2025-01-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_customuser_education_remove_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmaker',
            name='education',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formmaker',
            name='objective',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formmaker',
            name='projects',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formmaker',
            name='skills',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formmaker',
            name='tools',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
