# Generated by Django 5.1.5 on 2025-01-25 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_formmaker_education_alter_formmaker_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmaker',
            name='customuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formmaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
